name: Nightly documentation

on:
  push:
    branches:
      - 'dev/feature'
      - 'dev/patch'
      - 'enhancement/**'
      - 'feature/**'
      - 'fix/**'
    tags-ignore:
      - '**'

jobs:
    nightly-docs:
        if: "!contains(toJSON(github.event.commits.*.message), '[ci skip]')"
        runs-on: ubuntu-latest
        steps:
            - name: Configure workflow
              id: configuration
              env:
                DOCS_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
              run: |
                if [ -n "$DOCS_DEPLOY_KEY" ]
                then
                  echo "DOCS_DEPLOY_KEY_PRESENT=true" >> $GITHUB_OUTPUT
                else
                  echo "Secret 'DOCS_DEPLOY_KEY' not present. Exiting job."
                fi
                BRANCH_NAME="${GITHUB_REF#refs/*/}"
                echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
                echo "DOCS_OUTPUT_DIR=${GITHUB_WORKSPACE}/skript-docs/docs/nightly/${BRANCH_NAME}" >> $GITHUB_OUTPUT
                echo "DOCS_REPO_DIR=${GITHUB_WORKSPACE}/skript-docs" >> $GITHUB_OUTPUT
                echo "SKRIPT_REPO_DIR=${GITHUB_WORKSPACE}/skript" >> $GITHUB_OUTPUT
            - name: Checkout Skript
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  path: skript
            - name: Setup documentation environment
              if: steps.configuration.outputs.DOCS_DEPLOY_KEY_PRESENT == 'true'
              uses: ./skript/.github/workflows/docs/setup-docs
              with:
                  docs_deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
                  docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
            - name: Generate documentation
              id: generate
              if: steps.configuration.outputs.DOCS_DEPLOY_KEY_PRESENT == 'true'
              uses: ./skript/.github/workflows/docs/generate-docs
              with:
                  docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
                  docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
                  skript_repo_dir: ${{ steps.configuration.outputs.SKRIPT_REPO_DIR }}
            - name: Push nightly documentation
              if: steps.generate.outputs.DOCS_CHANGED == 'true'
              uses: ./skript/.github/workflows/docs/push-docs
              with:
                  docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
                  git_name: Nightly Docs Bot
                  git_email: nightlydocs@skriptlang.org
                  git_commit_message: "Update ${{ steps.configuration.outputs.BRANCH_NAME }} branch nightly docs to ${{ github.repository }}@${{ github.sha }}"
